--- 
abstract: catch your forked server's warnings
author: 
  - Shawn M Moore, C<< <sartak at bestpractical.com> >>
build_requires: 
  WWW::Mechanize: 0
distribution_type: module
generated_by: Module::Install version 0.70
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Test-HTTP-Server-Simple-StashWarnings
no_index: 
  directory: 
    - inc
    - t
requires: 
  HTTP::Server::Simple: 0.34
  Test::HTTP::Server::Simple: 0
  perl: 5.8.0
version: 0.03
